name: Heal
main: Heal\main
api: [3.0.0]
version: 1.0.0
author: Karanpatel567

commands:
 heal:
  description: Command to /heal
  aliases: ["max"]

permissions:
 heal.command:
  default: op
  description: The permission to /heal
 heal.other:
  default: op
  description: The permission to heal someone else
