name: Heal
main: Heal\main
api: [3.0.0-ALPHA8, 3.0.0-ALPHA7, 3.0.0-ALPHA9]
version: 2.0.0
author: Karanpatel567

commands:
 heal:
  description: Command to /heal
  aliases: ["max"]

permissions:
 heal.command:
  default: op
  description: The permission to /heal
 heal.other:
  default: op
  description: The permission to heal someone else
